puts "Makers Academy : May 2014 Cohort"
puts "================================"
puts "Faezrah Rizalman"
puts "Federico Maffei"
puts "James Keap"
puts "James Whyte"
puts "Jamie Patel"
puts "Johann Bornman"
puts "Josh Fail-Brown"
puts "Julia Tan"
puts "Julie Walker"
puts "Kate Hamilton"
puts "Margherita Serino"
puts "Nic Yeeles"
puts "Nicolai DTH"
puts "Roi Driscoll"
puts "Sasha Cooper"
puts "Vaidas Mykolaitis"
puts "Will Allen"
print "Overall we have "
print 19
puts " great students"